# Generated by Django 4.1.3 on 2023-04-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='type',
            new_name='caltype',
        ),
        migrations.CreateModel(
            name='WeeklyMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cal', models.DateField()),
                ('due_cal', models.DateField()),
                ('remark', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.department')),
            ],
            options={
                'ordering': ('due_cal',),
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='calibration',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='equipment.calibration'),
            preserve_default=False,
        ),
    ]
