# Generated by Django 4.1.3 on 2023-04-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_calibration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='equipment_id',
            new_name='equipment',
        ),
    ]
