# Generated by Django 4.1.3 on 2023-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_rename_equipment_id_calibration_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
