# Generated by Django 4.1.3 on 2023-04-12 08:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_calibration_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 12, 8, 18, 52, 269577, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
